version: '2'
services:
  Kafka:
    image: spotify/kafka
    hostname: kafka-server

    network_mode: bridge

    environment:
      - ADVERTISED_HOST=${KAFKA_HOST_IP}
      - ADVERTISED_PORT=9092
    ports:
      - "0.0.0.0:2181:2181"
      - "0.0.0.0:9092:9092"
    restart: always
  Mysql:
    image: mysql:5.6
    hostname: mysql-jobportal-server
    network_mode: bridge
    environment:
     MYSQL_DATABASE: jobs
     MYSQL_ROOT_PASSWORD: root
    links:
     - Kafka:kafka-server

    ports:
      - "0.0.0.0:3306:3306"
    depends_on:
      - Kafka
    restart: always
  Job_Portal:
    image: vickyramesh/jobportal:app-jobportal
    hostname: app-jobportal.local
    network_mode: bridge
    links:
     - Kafka:kafka-server
     - Mysql:mysql-jobportal-server
    depends_on:
      - Mysql
    ports:
      - "0.0.0.0:8050:8050"
    restart: always
